#Requires -Version 5.1
Set-StrictMode -Version Latest

<#
.SYNOPSIS
    Secrets + prerequisite helpers for the WSL DevOps Kit.
.DESCRIPTION
    Provides:
      - Get-KitSecretsStatus : inspect config/secrets.local.ps1 (exists / valid).
      - New-KitSecrets       : write a secrets file non-interactively (testable).
      - Request-KitSecrets   : prompt the user and write a secrets file.
      - Test-KitInteractive  : whether we may safely prompt the user.
      - Get-KitPrerequisite  : structured prerequisite checks (PowerShell/WSL/git/secrets).
    The substitution/validation logic is platform-agnostic so it can be tested
    off Windows (the interactive prompt simply isn't exercised there).
#>

function ConvertTo-Ps1SingleQuoted {
    # Render a value as a safe PowerShell single-quoted literal (handles $, ", ').
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Value)
    "'" + ($Value -replace "'", "''") + "'"
}

function Test-KitInteractive {
    [CmdletBinding()]
    [OutputType([bool])]
    param()
    # Explicit opt-out for CI / automated runs (also prevents tests from blocking on Read-Host).
    if ($env:KIT_NONINTERACTIVE -eq '1') { return $false }
    return ([Environment]::UserInteractive -and -not [Console]::IsInputRedirected)
}

function Get-KitSecretsStatus {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Path)

    $result = [ordered]@{
        Path          = $Path
        Exists        = $false
        HasPassword   = $false
        IsPlaceholder = $false
        IsValid       = $false
    }

    if (Test-Path -LiteralPath $Path) {
        $result.Exists = $true
        # Dot-source in a child scope so the kit variables do not leak into the caller.
        $pw = & {
            param($p)
            . $p
            if (Get-Variable -Name LinuxPassword -ErrorAction SilentlyContinue) { $LinuxPassword } else { $null }
        } $Path

        if (-not [string]::IsNullOrWhiteSpace($pw)) { $result.HasPassword = $true }
        if ($pw -eq 'CHANGE_ME') { $result.IsPlaceholder = $true }
        $result.IsValid = ($result.HasPassword -and -not $result.IsPlaceholder)
    }

    [pscustomobject]$result
}

function New-KitSecrets {
    # This function's sole job is to materialize a local dev secrets file, so it must
    # accept and persist the plaintext password. Suppress the credential-hardening rules.
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingUsernameAndPasswordParams', '', Justification = 'Secrets-file generator writes a plaintext password by design.')]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', 'LinuxPassword', Justification = 'Secrets-file generator writes a plaintext password by design.')]
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$LinuxPassword,
        [Parameter(Mandatory)][string]$GitUserName,
        [Parameter(Mandatory)][string]$GitUserEmail,
        [string]$SshKeyComment,
        [switch]$Force
    )

    if ((Test-Path -LiteralPath $Path) -and -not $Force) {
        throw ('Secrets file already exists: {0} (use -Force to overwrite).' -f $Path)
    }
    if ([string]::IsNullOrWhiteSpace($LinuxPassword) -or $LinuxPassword -eq 'CHANGE_ME') {
        throw 'LinuxPassword must be a real value (not empty and not "CHANGE_ME").'
    }
    if ([string]::IsNullOrWhiteSpace($SshKeyComment)) { $SshKeyComment = $GitUserEmail }

    $lines = @(
        '# Local secrets - never commit. Generated by scripts\new-secrets.ps1.'
        ('$LinuxPassword = {0}' -f (ConvertTo-Ps1SingleQuoted $LinuxPassword))
        ('$GitUserName   = {0}' -f (ConvertTo-Ps1SingleQuoted $GitUserName))
        ('$GitUserEmail  = {0}' -f (ConvertTo-Ps1SingleQuoted $GitUserEmail))
        ('$SshKeyComment = {0}' -f (ConvertTo-Ps1SingleQuoted $SshKeyComment))
    )

    $dir = Split-Path -Parent $Path
    if ($dir -and -not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }

    if ($PSCmdlet.ShouldProcess($Path, 'Write secrets file')) {
        Set-Content -LiteralPath $Path -Value $lines
        Write-Verbose ('Wrote secrets file: {0}' -f $Path)
    }
}

function Request-KitSecrets {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Path,
        [switch]$Force
    )

    if (-not (Test-KitInteractive)) {
        throw 'Cannot prompt for secrets in a non-interactive session. Run scripts\new-secrets.ps1 from an interactive PowerShell prompt, or create config\secrets.local.ps1 manually.'
    }

    Write-Host ('Creating {0}' -f $Path) -ForegroundColor Cyan
    Write-Host 'Enter the values below (input is not committed to git).'

    $secure = Read-Host -AsSecureString 'Linux user password'
    $pw     = [System.Net.NetworkCredential]::new('', $secure).Password
    $name   = Read-Host 'Git user.name'
    $email  = Read-Host 'Git user.email'
    $ssh    = Read-Host ('SSH key comment [{0}]' -f $email)
    if ([string]::IsNullOrWhiteSpace($ssh)) { $ssh = $email }

    New-KitSecrets -Path $Path -LinuxPassword $pw -GitUserName $name -GitUserEmail $email -SshKeyComment $ssh -Force:$Force
    Write-Host ('Wrote {0}' -f $Path) -ForegroundColor Green
}

function Get-KitPrerequisite {
    [CmdletBinding()]
    param([string]$SecretsPath)

    $checks = New-Object System.Collections.Generic.List[object]

    $checks.Add([pscustomobject]@{
        Name     = 'PowerShell >= 5.1'
        Required = $true
        Ok       = ($PSVersionTable.PSVersion -ge [version]'5.1')
        Detail   = $PSVersionTable.PSVersion.ToString()
    })

    $wsl = Get-Command wsl -ErrorAction SilentlyContinue
    $checks.Add([pscustomobject]@{
        Name     = 'WSL (wsl command)'
        Required = $true
        Ok       = [bool]$wsl
        Detail   = if ($wsl) { $wsl.Source } else { 'not found - install on Windows: wsl --install' }
    })

    $git = Get-Command git -ErrorAction SilentlyContinue
    $checks.Add([pscustomobject]@{
        Name     = 'git'
        Required = $false
        Ok       = [bool]$git
        Detail   = if ($git) { $git.Source } else { 'not found (recommended: Git for Windows)' }
    })

    if ($SecretsPath) {
        $st = Get-KitSecretsStatus -Path $SecretsPath
        $detail =
            if ($st.IsValid)   { 'present and valid' }
            elseif ($st.Exists) { 'present but LinuxPassword missing/placeholder' }
            else                { 'missing - run scripts\new-secrets.ps1' }
        $checks.Add([pscustomobject]@{
            Name     = 'config/secrets.local.ps1'
            Required = $true
            Ok       = $st.IsValid
            Detail   = $detail
        })
    }

    $checks.ToArray()
}

Export-ModuleMember -Function Get-KitSecretsStatus, New-KitSecrets, Request-KitSecrets, Test-KitInteractive, Get-KitPrerequisite
