#Requires -Version 5.1
Set-StrictMode -Version Latest

<#
.SYNOPSIS
    Secrets + prerequisite helpers for the WSL DevOps Kit.
.DESCRIPTION
    Provides:
      - Get-KitSecretsStatus : inspect config/secrets.local.ps1 (exists / valid).
      - New-KitSecrets       : write a secrets file non-interactively (testable).
      - Request-KitSecrets   : prompt the user and write a secrets file.
      - Test-KitInteractive  : whether we may safely prompt the user.
      - Get-KitPrerequisite  : structured prerequisite checks (PowerShell/WSL/git/secrets).
    The substitution/validation logic is platform-agnostic so it can be tested
    off Windows (the interactive prompt simply isn't exercised there).
#>

function ConvertTo-Ps1SingleQuoted {
    # Render a value as a safe PowerShell single-quoted literal (handles $, ", ').
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Value)
    "'" + ($Value -replace "'", "''") + "'"
}

function Test-KitInteractive {
    [CmdletBinding()]
    [OutputType([bool])]
    param()
    # Explicit opt-out for CI / automated runs (also prevents tests from blocking on Read-Host).
    if ($env:KIT_NONINTERACTIVE -eq '1') { return $false }
    return ([Environment]::UserInteractive -and -not [Console]::IsInputRedirected)
}

function Get-KitSecretsStatus {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Path)

    $result = [ordered]@{
        Path          = $Path
        Exists        = $false
        HasPassword   = $false
        IsPlaceholder = $false
        IsValid       = $false
    }

    if (Test-Path -LiteralPath $Path) {
        $result.Exists = $true
        # Dot-source in a child scope so the kit variables do not leak into the caller.
        $pw = & {
            param($p)
            . $p
            if (Get-Variable -Name LinuxPassword -ErrorAction SilentlyContinue) { $LinuxPassword } else { $null }
        } $Path

        if (-not [string]::IsNullOrWhiteSpace($pw)) { $result.HasPassword = $true }
        if ($pw -eq 'CHANGE_ME') { $result.IsPlaceholder = $true }
        $result.IsValid = ($result.HasPassword -and -not $result.IsPlaceholder)
    }

    [pscustomobject]$result
}

function New-KitSecrets {
    # This function's sole job is to materialize a local dev secrets file, so it must
    # accept and persist the plaintext password. Suppress the credential-hardening rules.
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingUsernameAndPasswordParams', '', Justification = 'Secrets-file generator writes a plaintext password by design.')]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', 'LinuxPassword', Justification = 'Secrets-file generator writes a plaintext password by design.')]
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$LinuxPassword,
        [Parameter(Mandatory)][string]$GitUserName,
        [Parameter(Mandatory)][string]$GitUserEmail,
        [string]$SshKeyComment,
        [switch]$Force
    )

    if ((Test-Path -LiteralPath $Path) -and -not $Force) {
        throw ('Secrets file already exists: {0} (use -Force to overwrite).' -f $Path)
    }
    if ([string]::IsNullOrWhiteSpace($LinuxPassword) -or $LinuxPassword -eq 'CHANGE_ME') {
        throw 'LinuxPassword must be a real value (not empty and not "CHANGE_ME").'
    }
    if ([string]::IsNullOrWhiteSpace($SshKeyComment)) { $SshKeyComment = $GitUserEmail }

    $lines = @(
        '# Local secrets - never commit. Generated by scripts\new-secrets.ps1.'
        ('$LinuxPassword = {0}' -f (ConvertTo-Ps1SingleQuoted $LinuxPassword))
        ('$GitUserName   = {0}' -f (ConvertTo-Ps1SingleQuoted $GitUserName))
        ('$GitUserEmail  = {0}' -f (ConvertTo-Ps1SingleQuoted $GitUserEmail))
        ('$SshKeyComment = {0}' -f (ConvertTo-Ps1SingleQuoted $SshKeyComment))
    )

    $dir = Split-Path -Parent $Path
    if ($dir -and -not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }

    if ($PSCmdlet.ShouldProcess($Path, 'Write secrets file')) {
        Set-Content -LiteralPath $Path -Value $lines
        Write-Verbose ('Wrote secrets file: {0}' -f $Path)
    }
}

function Request-KitSecrets {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Path,
        [switch]$Force
    )

    if (-not (Test-KitInteractive)) {
        throw 'Cannot prompt for secrets in a non-interactive session. Run scripts\new-secrets.ps1 from an interactive PowerShell prompt, or create config\secrets.local.ps1 manually.'
    }

    Write-Host ('Creating {0}' -f $Path) -ForegroundColor Cyan
    Write-Host 'Enter the values below (input is not committed to git).'

    $secure = Read-Host -AsSecureString 'Linux user password'
    $pw     = [System.Net.NetworkCredential]::new('', $secure).Password
    $name   = Read-Host 'Git user.name'
    $email  = Read-Host 'Git user.email'
    $ssh    = Read-Host ('SSH key comment [{0}]' -f $email)
    if ([string]::IsNullOrWhiteSpace($ssh)) { $ssh = $email }

    New-KitSecrets -Path $Path -LinuxPassword $pw -GitUserName $name -GitUserEmail $email -SshKeyComment $ssh -Force:$Force
    Write-Host ('Wrote {0}' -f $Path) -ForegroundColor Green
}

# --- Mockable probes (kept internal; tests mock these per-scenario) -----------

function Test-KitCommand {
    # Whether a command/binary is resolvable on PATH.
    [CmdletBinding()]
    [OutputType([bool])]
    param([Parameter(Mandatory)][string]$Name)
    [bool](Get-Command -Name $Name -ErrorAction SilentlyContinue)
}

function Get-KitOsInfo {
    # Operating-system facts (Windows caption + build number).
    [CmdletBinding()]
    param()
    $isWin = [System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform(
        [System.Runtime.InteropServices.OSPlatform]::Windows)
    $caption = $null
    $build   = $null
    if ($isWin) {
        try {
            $os = Get-CimInstance -ClassName Win32_OperatingSystem -ErrorAction Stop
            $caption = $os.Caption
            $build   = [int]$os.BuildNumber
        } catch {
            try { $build = [System.Environment]::OSVersion.Version.Build } catch { }
        }
    }
    [pscustomobject]@{ IsWindows = $isWin; Caption = $caption; Build = $build }
}

function Test-KitVirtualizationEnabled {
    # $true / $false / $null (unknown). WSL2 needs hardware virtualization.
    [CmdletBinding()]
    param()
    $fw = $null
    $hv = $null
    try {
        $cpu = Get-CimInstance -ClassName Win32_Processor -ErrorAction Stop | Select-Object -First 1
        if ($null -ne $cpu.VirtualizationFirmwareEnabled) { $fw = [bool]$cpu.VirtualizationFirmwareEnabled }
    } catch { }
    try {
        $cs = Get-CimInstance -ClassName Win32_ComputerSystem -ErrorAction Stop
        if ($null -ne $cs.HypervisorPresent) { $hv = [bool]$cs.HypervisorPresent }
    } catch { }
    if ($fw -eq $true -or $hv -eq $true)  { return $true }
    if ($fw -eq $false -or $hv -eq $false) { return $false }
    return $null
}

function Get-KitWslInfo {
    # WSL presence + whether the modern (Store) build with `wsl --version` is available.
    [CmdletBinding()]
    param()
    $installed     = Test-KitCommand -Name 'wsl'
    $hasVersionCmd = $false
    if ($installed) {
        try {
            & wsl.exe --version *> $null 2>&1
            $hasVersionCmd = ($LASTEXITCODE -eq 0)
        } catch { }
    }
    [pscustomobject]@{ Installed = $installed; HasVersionCommand = $hasVersionCmd }
}

function Test-KitDockerReady {
    # $true when the docker client resolves AND the daemon is reachable
    # (i.e. Docker Desktop is running with WSL integration enabled).
    [CmdletBinding()]
    [OutputType([bool])]
    param()
    if (-not (Test-KitCommand -Name 'docker')) { return $false }
    try {
        & docker info *> $null 2>&1
        return ($LASTEXITCODE -eq 0)
    } catch { return $false }
}

# --- Composed prerequisite report --------------------------------------------

function Get-KitPrerequisite {
    [CmdletBinding()]
    param([string]$SecretsPath)

    $checks = New-Object System.Collections.Generic.List[object]
    $add = {
        param($Name, $Required, $Ok, $Detail)
        $checks.Add([pscustomobject]@{ Name = $Name; Required = $Required; Ok = $Ok; Detail = $Detail })
    }

    # PowerShell
    & $add 'PowerShell >= 5.1' $true ($PSVersionTable.PSVersion -ge [version]'5.1') $PSVersionTable.PSVersion.ToString()

    # Windows OS + supported build (Win10 21H2 build 19044 / Win11)
    $os = Get-KitOsInfo
    & $add 'Operating system: Windows' $true $os.IsWindows ($(if ($os.IsWindows) { $os.Caption } else { 'not Windows - this kit provisions WSL on a Windows host' }))
    $buildOk = ($os.IsWindows -and $os.Build -ge 19044)
    $buildDetail =
        if (-not $os.IsWindows) { 'n/a (not Windows)' }
        elseif ($null -eq $os.Build) { 'could not determine build' }
        elseif ($buildOk) { ('build {0}' -f $os.Build) }
        else { ('build {0} - need Win10 21H2 (19044)+ or Win11' -f $os.Build) }
    & $add 'Windows build >= 19044 (21H2/Win11)' $true $buildOk $buildDetail

    # Hardware virtualization (downgraded to a warning when it can't be determined)
    $vt = Test-KitVirtualizationEnabled
    if ($vt -eq $true)       { & $add 'Hardware virtualization' $true  $true  'enabled' }
    elseif ($vt -eq $false)  { & $add 'Hardware virtualization' $true  $false 'disabled - enable VT-x/AMD-V in BIOS/UEFI' }
    else                     { & $add 'Hardware virtualization' $false $false 'could not determine (verify on the Windows host)' }

    # WSL command + modern Store build
    $wsl = Get-KitWslInfo
    & $add 'WSL (wsl command)' $true $wsl.Installed ($(if ($wsl.Installed) { 'installed' } else { 'not found - run: wsl --install' }))
    & $add 'WSL2 (Store build, `wsl --version`)' $false $wsl.HasVersionCommand ($(if ($wsl.HasVersionCommand) { 'modern WSL detected (systemd-capable)' } else { 'run "wsl --update" / install WSL from the Microsoft Store' }))

    # Git for Windows (credential manager + clones)
    $git = Test-KitCommand -Name 'git'
    & $add 'Git for Windows' $true $git ($(if ($git) { 'found' } else { 'not found - install Git for Windows' }))

    # Docker Desktop (manual post-install step, so only a recommendation)
    $docker = Test-KitDockerReady
    & $add 'Docker Desktop (running + WSL integration)' $false $docker ($(if ($docker) { 'docker daemon reachable' } else { 'not ready - install Docker Desktop and enable WSL integration (post-install)' }))

    # Windows Terminal (recommended)
    $wt = Test-KitCommand -Name 'wt'
    & $add 'Windows Terminal (recommended)' $false $wt ($(if ($wt) { 'found' } else { 'not found - optional, install from the Microsoft Store' }))

    # Kit secrets
    if ($SecretsPath) {
        $st = Get-KitSecretsStatus -Path $SecretsPath
        $detail =
            if ($st.IsValid)   { 'present and valid' }
            elseif ($st.Exists) { 'present but LinuxPassword missing/placeholder' }
            else                { 'missing - run scripts\new-secrets.ps1' }
        & $add 'config/secrets.local.ps1' $true $st.IsValid $detail
    }

    $checks.ToArray()
}

Export-ModuleMember -Function Get-KitSecretsStatus, New-KitSecrets, Request-KitSecrets, Test-KitInteractive, Get-KitPrerequisite
